import type {Metadata} from "next";
import {Ubuntu} from "next/font/google";
import "./globals.css";


const ubuntu = Ubuntu({
    weight: ["300", "400", "500", "700"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "TeeFusion | DDnet | Teeworlds",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={ubuntu.className}>
        {children}
        </body>
        </html>
    );
}
